'''
Compute the Horton-Strahler stream order of 
a tree generated by CCO from its .cco file.
'''

import sys
from tools import ReadTree, StrahlerOrder, TreeStatistics, PlotTreeStatistics


assert(len(sys.argv)>1)
ccoFile = sys.argv[1]

# Read tree connectivity
treeData, treeConnectivity = ReadTree(ccoFile)

treeData = [[0, 0.5, 1.0, 0.0],
            [1, 0.2, 1.0, 0.0],
            [2, 0.5, 1.0, 0.0],
            [3, 0.4, 1.0, 0.0],
            [4, 0.3, 1.0, 0.0],
            [5, 0.2, 1.0, 0.0],
            [6, 0.2, 1.0, 0.0],
            [7, 0.3, 1.0, 0.0],
            [8, 0.2, 1.0, 0.0],
            [9, 0.2, 1.0, 0.0],
            [10, 0.4, 1.0, 0.0],
            [11, 0.1, 1.0, 0.0],
            [12, 0.4, 1.0, 0.0],
            [13, 0.3, 1.0, 0.0],
            [14, 0.2, 1.0, 0.0],
            [15, 0.2, 1.0, 0.0],
            [16, 0.3, 1.0, 0.0],
            [17, 0.2, 1.0, 0.0],
            [18, 0.2, 1.0, 0.0]]

treeConnectivity = [[0, -1, [1,2]],
                    [1, 0, []],
                    [2, 0, [3,10]],
                    [3, 2, [4,7]],
                    [4, 3, [5,6]],
                    [5, 4, []],
                    [6, 4, []],
                    [7, 3, [9,8]],
                    [8, 7, []],
                    [9, 7, []],
                    [10, 2, [11,12]],
                    [11, 10, []],
                    [12, 10, [13, 16]],
                    [13, 12, [14, 15]],
                    [14, 13, []],
                    [15, 13, []],
                    [16, 12, [17, 18]],
                    [17, 16, []],
                    [18, 16, []]]

orderedTree = StrahlerOrder(treeData, treeConnectivity)
# stats = TreeStatistics(orderedTree, treeData)
PlotTreeStatistics(orderedTree)

for i in orderedTree:
    print(i[0], i[-1])
