'''
Compute the Horton-Strahler stream order of 
a tree generated by CCO from its .cco file.
'''

import sys
from tools import ReadTree, StrahlerOrder, TreeStatistics, PlotTreeStatistics


assert(len(sys.argv)>1)
ccoFile = sys.argv[1]

# Read tree connectivity
treeData, treeConnectivity = ReadTree(ccoFile)


orderedTree = StrahlerOrder(treeData, treeConnectivity)
# stats = TreeStatistics(orderedTree, treeData)
PlotTreeStatistics(orderedTree)
